<?php

namespace App\Notifications;

use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Notifications\Messages\MailMessage;

/**
 * Branded email-verification notification.
 *
 * Extends Laravel's built-in VerifyEmail so it reuses the framework's signed,
 * expiring verification URL (built from config('app.url') — keep APP_URL correct
 * in production) while presenting Planetic Web branding. Intentionally NOT queued
 * so delivery does not depend on a running queue worker; the send is wrapped in a
 * try/catch in User::sendEmailVerificationNotification() so a mail failure can
 * never turn registration or a resend into a 500.
 */
class VerifyEmailNotification extends VerifyEmail
{
    /**
     * @param  string  $url  The signed verification URL generated by the parent.
     */
    protected function buildMailMessage($url): MailMessage
    {
        $appName = config('app.name', 'Planetic Web');

        return (new MailMessage)
            ->subject('Verify your email address · '.$appName)
            ->greeting('Welcome to '.$appName.'!')
            ->line('Thanks for creating an account. Please confirm your email address to activate your account and access your dashboard.')
            ->action('Verify email address', $url)
            ->line('This secure link will expire in 60 minutes.')
            ->line('If you did not create an account, no further action is required and you can safely ignore this email.')
            ->salutation('— The '.$appName.' team');
    }
}
