<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $invoice->invoice_number }} · {{ config('app.name') }}</title>
    @vite(['resources/css/app.css'])
    <style>@media print { .no-print { display: none; } }</style>
</head>
<body class="bg-white p-8 text-slate-900">
    <div class="mx-auto max-w-2xl">
        <div class="flex items-start justify-between">
            <div>
                <p class="text-xl font-extrabold">Planetic<span class="text-primary-500">Web</span></p>
                <p class="text-sm text-slate-500">planeticweb.com</p>
            </div>
            <div class="text-right">
                <h1 class="text-2xl font-bold">Invoice</h1>
                <p class="text-sm text-slate-500">{{ $invoice->invoice_number }}</p>
                <p class="text-sm text-slate-500">{{ $invoice->created_at->format('j M Y') }}</p>
            </div>
        </div>

        <div class="mt-8 grid grid-cols-2 gap-4 text-sm">
            <div>
                <p class="font-semibold text-slate-500">Billed to</p>
                <p class="font-medium">{{ $invoice->user->name }}</p>
                @if ($invoice->user->company_name)<p>{{ $invoice->user->company_name }}</p>@endif
                <p>{{ $invoice->user->email }}</p>
            </div>
            <div class="text-right">
                <p class="font-semibold text-slate-500">Status</p>
                <p class="font-medium">{{ $invoice->status->label() }}</p>
            </div>
        </div>

        <table class="mt-8 w-full text-sm">
            <thead class="border-b-2 border-slate-200 text-left">
                <tr><th class="py-2">Description</th><th class="py-2 text-right">Amount</th></tr>
            </thead>
            <tbody>
                @forelse ($invoice->order?->items ?? [] as $item)
                    <tr class="border-b border-slate-100"><td class="py-2">{{ $item->name }}</td><td class="py-2 text-right">£{{ number_format((float) $item->total, 2) }}</td></tr>
                @empty
                    <tr class="border-b border-slate-100"><td class="py-2">{{ $invoice->order?->order_number ?? 'Service' }}</td><td class="py-2 text-right">£{{ number_format((float) $invoice->subtotal, 2) }}</td></tr>
                @endforelse
            </tbody>
        </table>

        <div class="mt-4 ml-auto max-w-xs text-sm">
            <div class="flex justify-between border-t-2 border-slate-200 py-2 text-base font-bold"><span>Total</span><span>£{{ number_format((float) $invoice->total, 2) }}</span></div>
        </div>

        <p class="mt-12 text-center text-xs text-slate-400">Thank you for your business. This invoice was generated by {{ config('app.name') }}.</p>
        <button onclick="window.print()" class="no-print btn-primary mt-8">Print this invoice</button>
    </div>
</body>
</html>
